### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by nairo-mudumane** [kishannareshpal/ExamesGithub#1]
Hi, I recently downloaded your app and I have some good ideas, but I see that this is the last open version of the project. How do I contribute to the latest version?

**Comment by kishannareshpal** [comment]
Hey @nairo-mudumane,
Ah yes, this is an archive of the very first version of the app. The newer (v2) that's currently rolled out is going to remain private and closed (at least for now). I'm in the process of releasing v3 so I might change my mind and open-source v2 later on 😛 (who knows).

Anyhow sorry for the late response, I've only looked at this repo by chance today and saw your comment.
Happy to discuss more, please reach me at kishan_jadav@hotmail.com or by my twitter handle [@theredpand4](https://twitter.com/theredpand4).

Thanks
